version: "3.8"

services:
  app:
    build: .
    command: ./server
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
      - redis

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  mongodata:
